# config/packages/doctrine.yaml
doctrine:
  dbal:
    driver: 'pdo_mysql'
    server_version: '8.0'
    charset: utf8mb4

    # >>> Paramètres via variables d'environnement (pas d'URL !)
    host: '%env(string:DB_HOST)%'
    port: '%env(int:DB_PORT)%'
    dbname: '%env(string:DB_NAME)%'
    user: '%env(string:DB_USER)%'
    password: '%env(DB_PASSWORD)%'

    # Sécurité : s'assurer qu'aucun "url" hérité ne traîne
    url: ~   # (nul) désactive toute URL héritée

  orm:
    auto_generate_proxy_classes: true
    enable_lazy_ghost_objects: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      App:
        is_bundle: false
        type: attribute
        dir: '%kernel.project_dir%/src/Entity'
        prefix: 'App\Entity'
        alias: App
